[package]
name = "mercury-sys"
version = "0.1.0"
edition = "2021"
links = "mercurry"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.60"
cmake = "0.1"
