[package]
name = "mercury-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mercury-sys ={ path = "mercury-sys"}

[workspace]
members = ["mercury-sys"]
